### PR TITLE
Add support for zoho expense api 

### PR DESCRIPTION
**Pull request by ashishsnigam**
First draft towards adding support of Zoho expense API. 
1) Added expense API list_all_expenses to list all expenses report for a given organization id
2) Added expense API GetOrganization to get organization_id to be passed in all expense api
3) Updated zoho struct to have additional field for organization id
4) Added method SetOrganizationId to update zoho struct to have additional field for organization id
5) Added new scopes for expense api
6) Fix variable assignment issue in existing code

### CODE REVIEW

**Comment by schmorrison** [comment]
Thanks for the PR!! I will review in the morning.

**Review by schmorrison — CHANGES_REQUESTED** [review]
Great work @ashishsnigam.  I just have a couple things I would like to see changed.

In oauth2.go line 290 and 293 were changed from type alias format. It may have been GoFmt from an older version of Go that made the change, or maybe you are running an older version of Go that doesn't know about type aliases. Because the type `SettingsMethod` and `ModulesMethod` are not actually different, they just expose a different namespace for semantic reasons, I wrote them as aliases rather than extended types.

Also in expense/expense.go I would like to see a `type expenseModule string` provided at the top, and each const module declaration should be that type and not string.

Finally I was wondering if you think it might reduce future clutter if we move the Scopes, SettingsMethods, and ModuleMethods to their respective packages now. It could reduce namespace clashing in the future when additional packages are added. **_You do not have to do this, I am just asking for your perspective, I can make that change in the future._**

Again, thanks for your pull request and we will get it merged as soon as you provide those small changes.

Best regards,
Sam Morrison

**Comment by ashishsnigam** [comment]
@schmorrison ,

I have incorporated your review comments. Also agreed with you on moving Scopes, Settings methods as you suggested. In addition, I can help you in putting more APIs there. Just find out the most used or requested ones and I will try to incorporate them also.

Thanks,
Ashish

**Comment by schmorrison** [comment]
Awesome, thanks for your contribution @ashishsnigam.

**Pull request merged**
